/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javautils;
import java.util.function.Consumer;
import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

public class SparkJob {

    public SparkJob(Consumer<SparkUtilities> executor){
        SparkUtilities utils = new SparkUtilities();
        Weld di = new Weld();
        executor.accept(utils);
        // try(WeldContainer container = di.initialize()){
            // container.select(SparkUtilities.class).get();
            // executor.accept(utils);
        // }
    }
}
