/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("cloud.emtech.job.scala-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
    implementation(project(":javautils"))
}

application {
    // Define the main class for the application.
    mainClass.set("cloud.emtech.job.reporting.App")
}
