/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package cloud.emtech.job.locationimport

import cloud.emtech.job.utilities.StringUtils

object App {
   def main(args: Array[String]): Unit = {
        val tokens = StringUtils.split(MessageUtils.getMessage())
        println(StringUtils.join(tokens))
    }
}
