/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package cloud.emtech.job.reporting

import cloud.emtech.job.utilities.StringUtils
import javautils._

object App {
   def main(args: Array[String]): Unit = {
        val tokens = StringUtils.split(MessageUtils.getMessage())
        println(StringUtils.join(tokens))
        val javaLib = new SparkJob(execute);
    }
   
    def execute(sparkUtils: SparkUtilities): Unit = {

    }
}
